### PR TITLE
A few small suggestions

### PR DESCRIPTION
**Pull request by MAgojam**
Hey Vincent,
Thank you for making this module available for jamovi.
I stopped by to take a look, as you asked in the FORUM.
Surely @jonathon-love will be able to give you some advice or suggestion to continue developing modules for jamovi.

In this PR (**feel free to reject it**) there are little things, especially to avoid plot flash if there are no choices or changes that specifically affect it.
I hope to see more of your stuff.

Cheers,
Maurizio

### CODE REVIEW

**Review by vjalby — APPROVED** [review]
Wow, thanks for these suggestions. I'm just not sure about min/max for height and width, cause it produces weird error message in jamovi output. I'll check it again.

**Comment by MAgojam** [comment]
> I'm just not sure about min/max for height and width, cause it produces weird error message in jamovi output.

Yes, it is.
The use of **min:** and **max:** in the **.a.yaml** file is intended to raise the error if the imputed value is out of range.

**Comment by vjalby** [comment]
Yes,  but I find the error message not "(end) user friendly", showing R code  and "DEBUG" message. I think it should just tell the user about the wrong value he entered and not let him think there's a bug in the R Code. But, just my point of view :)

**Comment by jonathon-love** [comment]
hey, i posted some feedback here: https://forum.jamovi.org/viewtopic.php?t=3619

although maybe it would have been better to post it here.

**Pull request merged**
